#!/bin/sh
COMMONFLAGS="-DCONFIG_CHECK_STACK_INTEGRITY -checks -exportlocal"

# check c28x
ARCH=arch/c2000/c28x
SPLINTFLAGS="${COMMONFLAGS} -I. -I${ARCH} -I${ARCH}/samples"
splint $SPLINTFLAGS picoRTOS.c $ARCH/picoRTOS_port.c

# check cm0+
ARCH=arch/arm/cm0+
SPLINTFLAGS="${COMMONFLAGS} -I. -I${ARCH} -I${ARCH}/samples"
splint $SPLINTFLAGS picoRTOS.c $ARCH/picoRTOS_port.c

# check ppc
ARCH=arch/ppc/e200
SPLINTFLAGS="${COMMONFLAGS} -I. -I${ARCH} -I${ARCH}/samples"
# ppc z4
splint $SPLINTFLAGS picoRTOS.c $ARCH/picoRTOS_port.c $ARCH/timer/timer-pit.c $ARCH/intc/intc-mpc574xx.c
# ppc z7
splint $SPLINTFLAGS picoRTOS.c $ARCH/picoRTOS_port.c $ARCH/timer/timer-pit.c $ARCH/intc/intc-mpc5777x.c
# ppc z4 SMP
splint $SPLINTFLAGS picoRTOS-SMP.c $ARCH/picoRTOS_port.c $ARCH/timer/timer-pit.c $ARCH/intc/intc-mpc574xx.c $ARCH/core/core-mcme.c
# ppc z7 SMP
splint $SPLINTFLAGS picoRTOS-SMP.c $ARCH/picoRTOS_port.c $ARCH/timer/timer-pit.c $ARCH/intc/intc-mpc5777x.c $ARCH/core/core-siu.c
